import fs from 'fs';
import path from 'path';
import { dbService } from '../../services/db.service.js';
import { logger } from '../../utils/logger.js';

export class TelegramService {
  /**
   * Helper to normalize Telegram Bot Token
   * Strips 'bot' prefix, full URL prefixes, quotes, whitespace, and invisible characters
   */
  static normalizeToken(token) {
    if (!token) return '';
    let cleaned = token.trim();
    // Remove surrounding single or double quotes
    cleaned = cleaned.replace(/^["']|["']$/g, '');
    // If full URL was pasted: https://api.telegram.org/bot123456789:ABC.../getMe
    if (cleaned.includes('api.telegram.org/bot')) {
      const match = cleaned.match(/bot([^/]+)/);
      if (match) cleaned = match[1];
    }
    // Remove leading 'bot' prefix if user typed bot123456789:ABC...
    if (/^bot\d+:/i.test(cleaned)) {
      cleaned = cleaned.substring(3);
    }
    // Strip zero-width / non-printable whitespace characters
    cleaned = cleaned.replace(/[\u200B-\u200D\uFEFF]/g, '');
    return cleaned.trim();
  }

  /**
   * Helper to normalize channel ID or handle URL inputs
   */
  static normalizeChannelId(channelId) {
    if (!channelId) return '';
    let cleaned = channelId.trim();
    if (cleaned.startsWith('https://t.me/') || cleaned.startsWith('http://t.me/')) {
      const pathPart = cleaned.replace(/^https?:\/\/t\.me\//, '');
      if (pathPart.startsWith('+') || pathPart.startsWith('joinchat/')) {
        return cleaned; // Keep original invite link to report specific error
      }
      return '@' + pathPart.replace(/^@/, '');
    }
    return cleaned;
  }

  /**
   * Delete file/message from Telegram Channel
   */
  static async deleteMessageFromTelegram(messageId, overrideChannelId = null) {
    if (!messageId) return false;
    try {
      const settings = dbService.getSettings();
      const rawToken = settings.telegram_token || process.env.TELEGRAM_BOT_TOKEN;
      const token = TelegramService.normalizeToken(rawToken);
      const channelId = overrideChannelId || settings.telegram_channel_id || process.env.TELEGRAM_CHANNEL_ID;
      const targetChannel = TelegramService.normalizeChannelId(channelId);

      if (!token || !targetChannel) {
        logger.info('Telegram Bot Token or Channel ID not set. Skipping Telegram cloud message deletion.');
        return false;
      }

      const res = await fetch(`https://api.telegram.org/bot${token}/deleteMessage?chat_id=${encodeURIComponent(targetChannel)}&message_id=${encodeURIComponent(messageId)}`);
      const data = await res.json();
      if (data.ok) {
        logger.info(`Deleted message ID ${messageId} from Telegram Channel ${targetChannel}`);
        return true;
      } else {
        logger.warn(`Could not delete message ${messageId} from Telegram: ${data.description}`);
        return false;
      }
    } catch (err) {
      logger.error(`Error deleting message from Telegram: ${err.message}`);
      return false;
    }
  }

  /**
   * Test connection to Telegram Bot API
   */
  static async testConnection(rawToken, channelId) {
    const token = TelegramService.normalizeToken(rawToken);
    if (!token) {
      return { success: false, message: 'Bot Token is missing' };
    }
    if (token.includes('***')) {
      return { success: false, message: 'Token contains masked asterisks. Please enter your full Telegram Bot Token.' };
    }
    try {
      const meRes = await fetch(`https://api.telegram.org/bot${token}/getMe`);
      const meData = await meRes.json();
      if (!meData.ok) {
        let desc = meData.description || 'Invalid token';
        if (meData.error_code === 401 || desc.toLowerCase().includes('unauthorized')) {
          desc = 'Unauthorized (Token is invalid or revoked. If you revoked the bot token in BotFather, please enter the new token generated by BotFather).';
        }
        return { success: false, message: `Telegram API Error: ${desc}` };
      }

      const normalizedChannel = TelegramService.normalizeChannelId(channelId);
      let chatInfo = null;

      if (normalizedChannel) {
        if (normalizedChannel.includes('t.me/+') || normalizedChannel.includes('joinchat')) {
          return {
            success: false,
            bot: meData.result,
            message: `Bot connected (@${meData.result.username}), BUT Channel Error: Telegram invite links (t.me/+) cannot be used as Chat IDs. Use a public handle (@mychannel) or numeric Chat ID (-100xxxxxxxxxx).`
          };
        }

        const chatRes = await fetch(`https://api.telegram.org/bot${token}/getChat?chat_id=${encodeURIComponent(normalizedChannel)}`);
        const chatData = await chatRes.json();
        if (chatData.ok) {
          chatInfo = chatData.result.title || chatData.result.username || normalizedChannel;
        } else {
          logger.warn(`Could not verify channel ID ${normalizedChannel}: ${chatData.description}`);
          return {
            success: false,
            bot: meData.result,
            message: `Bot connected (@${meData.result.username}), BUT Channel Error (${chatData.description}). Make sure the Bot is added as an Administrator to the channel.`
          };
        }
      }

      return {
        success: true,
        bot: meData.result,
        channel: chatInfo,
        message: `Connected to @${meData.result.username}${chatInfo ? ` (Channel: ${chatInfo})` : ''}`
      };
    } catch (err) {
      return { success: false, message: `Network/Fetch Error: ${err.message}` };
    }
  }

  /**
   * Send file to Telegram Channel or Fallback to Simulated Storage
   */
  static async uploadFileToTelegram(filePath, originalFilename, mediaType, overrideChannelId = null) {
    const settings = dbService.getSettings();
    const rawToken = settings.telegram_token || process.env.TELEGRAM_BOT_TOKEN;
    const token = TelegramService.normalizeToken(rawToken);
    const channelId = overrideChannelId || settings.telegram_channel_id || process.env.TELEGRAM_CHANNEL_ID;
    const targetChannel = TelegramService.normalizeChannelId(channelId);

    // Check if real Telegram credentials are present and valid
    if (token && targetChannel && !targetChannel.includes('t.me/+') && !targetChannel.includes('joinchat')) {
      try {
        logger.info(`Sending file ${originalFilename} to Telegram Channel ${targetChannel}...`);
        
        const blob = new Blob([fs.readFileSync(filePath)]);
        const formData = new FormData();
        formData.append('chat_id', targetChannel);
        formData.append('document', blob, originalFilename);
        formData.append('caption', `📦 Uploaded via Telegram Cloud Storage\n📄 File: ${originalFilename}\n⚡ Media: ${mediaType}`);

        const telegramEndpoint = `https://api.telegram.org/bot${token}/sendDocument`;
        const res = await fetch(telegramEndpoint, {
          method: 'POST',
          body: formData
        });

        const data = await res.json();
        if (data.ok && data.result) {
          const result = data.result;
          const msgId = result.message_id.toString();
          let fileId = 'TG_FILE_UNKNOWN';
          if (result.document) fileId = result.document.file_id;
          else if (result.video) fileId = result.video.file_id;
          else if (result.photo) fileId = result.photo[result.photo.length - 1].file_id;
          else if (result.audio) fileId = result.audio.file_id;

          logger.info(`Successfully sent to Telegram! Message ID: ${msgId}, File ID: ${fileId}`);
          return {
            mode: 'telegram',
            telegram_message_id: msgId,
            telegram_file_id: fileId
          };
        } else {
          logger.warn(`Telegram upload failed (${data.description || 'chat not found'}). Using Simulated Storage fallback.`);
        }
      } catch (err) {
        logger.error(`Error sending to Telegram API: ${err.message}. Using Simulated Storage fallback.`);
      }
    } else if (targetChannel && (targetChannel.includes('t.me/+') || targetChannel.includes('joinchat'))) {
      logger.warn(`Telegram channel ID "${targetChannel}" is an invite link. Invite links cannot be used as Chat IDs. Using Simulated Storage.`);
    } else {
      logger.info(`Telegram Bot Token or Channel ID not configured. Using Simulated Storage.`);
    }

    // Simulated Telegram Storage Mode
    const simMsgId = Math.floor(100000 + Math.random() * 900000).toString();
    const simFileId = `SIM_TG_${mediaType.toUpperCase()}_${Date.now()}`;
    return {
      mode: 'simulated',
      telegram_message_id: simMsgId,
      telegram_file_id: simFileId
    };
  }

  /**
   * Get Download Stream / File Path from Telegram or Local Fallback
   */
  static async getDownloadStream(fileRecord) {
    const settings = dbService.getSettings();
    const rawToken = settings.telegram_token || process.env.TELEGRAM_BOT_TOKEN;
    const token = TelegramService.normalizeToken(rawToken);

    // Check if real telegram file id and token exist
    if (token && fileRecord.telegram_file_id && !fileRecord.telegram_file_id.startsWith('SIM_TG_')) {
      try {
        const fileInfoRes = await fetch(`https://api.telegram.org/bot${token}/getFile?file_id=${fileRecord.telegram_file_id}`);
        const fileInfo = await fileInfoRes.json();
        if (fileInfo.ok && fileInfo.result && fileInfo.result.file_path) {
          const downloadUrl = `https://api.telegram.org/file/bot${token}/${fileInfo.result.file_path}`;
          const streamRes = await fetch(downloadUrl);
          if (streamRes.ok) {
            return {
              isRemote: true,
              stream: streamRes.body
            };
          }
        }
      } catch (err) {
        logger.error(`Error fetching file stream from Telegram: ${err.message}`);
      }
    }

    // Return local fallback stream if available in local storage
    if (fileRecord.local_path && fs.existsSync(fileRecord.local_path)) {
      return {
        isRemote: false,
        localPath: fileRecord.local_path
      };
    }

    return null;
  }
}
